CREATE TABLE `hunt_fish_slots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`activity` enum('duck','deer','turkey','dove','quail','hog','bass','catfish','crappie','general_hunt','general_fish','hunt_and_fish') NOT NULL,
	`label` varchar(255) NOT NULL,
	`slotDate` date NOT NULL,
	`slotEndDate` date,
	`checkInTime` time,
	`checkOutTime` time,
	`totalCapacity` int NOT NULL DEFAULT 6,
	`bookedCount` int NOT NULL DEFAULT 0,
	`season` enum('spring','summer','fall','winter','year_round') NOT NULL DEFAULT 'fall',
	`regulatoryNotes` text,
	`pricePerPerson` decimal(10,2),
	`currency` varchar(3) DEFAULT 'USD',
	`resourceId` int,
	`guideNotes` text,
	`isPublic` boolean NOT NULL DEFAULT true,
	`isActive` boolean NOT NULL DEFAULT true,
	`notes` text,
	`createdByUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `hunt_fish_slots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `trip_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slotId` int NOT NULL,
	`userId` int NOT NULL,
	`memberId` int,
	`partySize` int NOT NULL DEFAULT 1,
	`guestNames` json,
	`hasMinors` boolean NOT NULL DEFAULT false,
	`huntingLicenseConfirmed` boolean NOT NULL DEFAULT false,
	`fishingLicenseConfirmed` boolean NOT NULL DEFAULT false,
	`waiverSignedAt` timestamp,
	`status` enum('pending','confirmed','declined','waitlisted','cancelled','no_show','completed') NOT NULL DEFAULT 'pending',
	`reviewedByUserId` int,
	`reviewedAt` timestamp,
	`declineReason` text,
	`staffNotes` text,
	`memberNotes` text,
	`confirmationSentAt` timestamp,
	`paymentStatus` enum('not_required','pending','paid','refunded','waived') NOT NULL DEFAULT 'not_required',
	`amountDue` decimal(10,2),
	`amountPaid` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `trip_requests_id` PRIMARY KEY(`id`)
);
