export type {
  CmsAmenity,
  InsertCmsAmenity,
  CmsLodgingUnit,
  InsertCmsLodgingUnit,
  CmsEventSpace,
  InsertCmsEventSpace,
  CmsPackage,
  InsertCmsPackage,
  CmsGallery,
  InsertCmsGallery,
  CmsGalleryImage,
  InsertCmsGalleryImage,
  CmsTestimonial,
  InsertCmsTestimonial,
  CmsFaq,
  InsertCmsFaq,
  CmsPolicy,
  InsertCmsPolicy,
  CmsAnnouncement,
  InsertCmsAnnouncement,
  CmsContactRoute,
  InsertCmsContactRoute,
  CmsMemberContent,
  InsertCmsMemberContent,
  CmsSingleton,
  InsertCmsSingleton,
} from "./schema";
